name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Plugin Map wc
      run: go build -buildmode=plugin -o wc_map.so wc_map.go 
    - name: Build Plugin Reduce wc
      run: go build -buildmode=plugin -o wc_reduce.so wc_reduce.go 
    - name: Build Plugin Map rwl
      run: go build -buildmode=plugin -o rwl_map.so rwl_map.go 
    - name: Build Plugin Reduce rwl
      run: go build -buildmode=plugin -o rwl_reduce.so rwl_reduce.go 
    - name: Build Main
      run: go build -v util.go membership.go SDFS.go mapleJuice.go

    - name: Test
      run: go test -v .
